import type { NextPage } from 'next'
import Head from 'next/head'
import { LinkIcon } from '@heroicons/react/solid'
import { useState } from 'react'

import Swal from 'sweetalert2'



const Home: NextPage = () => {

  const [phone, setPhone] = useState('');
  const [text, setText] = useState('');

  async function createLink(e){
    e.preventDefault();
    let defaulURL = `https://api.whatsapp.com/send/?phone=+55${phone}&text=${text}&app_absent=0`

    Swal.fire({
      title: 'Your Personal Link',
      text: `${defaulURL}`,
      icon: 'success',
      confirmButtonColor: '#3085d6',
      confirmButtonText: 'Copy!'
    }).then((result) => {
      if (result.isConfirmed) {
        navigator.clipboard.writeText(defaulURL)
        Swal.fire(
          'Copied!',
          'Your link has been copied to clipboard.',
          'success'
        )
      }
    })
  }


  return (
    <div >
      <Head>
        <title>Wtsp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <div className="min-h-full flex items-center justify-center py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-md w-full space-y-8">
          <div>
            <img
              className="mx-auto h-12 w-auto"
              src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
              alt="Workflow"
            />
            <h2 className="mt-6 text-center text-3xl font-extrabold text-gray-900">Start by telling us your phone</h2>
            <p className="mt-2 text-center text-sm text-gray-600">
              Or{' '}
              <a href="https://cloud.google.com/security/compliance/lgpd" target="_blank" className="font-medium text-indigo-600 hover:text-indigo-500">
                Don't worry, we don't store your data.
              </a>
            </p>
          </div>
          <form className="mt-8 space-y-6" onSubmit={createLink} >
            <input type="hidden" name="remember" defaultValue="true" />
            <div className="rounded-md shadow-sm -space-y-px">
              <div>
                <label htmlFor="email-address" className="sr-only">
                  Phone Number
                </label>
                <input
                  id="phone-number"
                  name="pnumber"
                  type="tel"
                  autoComplete="phone"
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="(86)99999-9999"
                  value={phone}
                  onChange={e => setPhone(e.target.value)}
                />
              </div>
              <div>
                <label htmlFor="text" className="sr-only">
                  Text
                </label>
                <textarea
                  id="text"
                  name="text"
                  rows={3}
                  required
                  className="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                  placeholder="Hello I would like to hire your services"
                  value={text}
                  onChange={e => setText(e.target.value)}
                />
              </div>
            </div>

            <div>
              <button
                type="submit"
                className="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
              >
                <span className="absolute left-0 inset-y-0 flex items-center pl-3">
                  <LinkIcon className="h-5 w-5 text-indigo-500 group-hover:text-indigo-400" aria-hidden="true" />
                </span>
                Get Link
              </button>
            </div>
          </form>
        </div>
      </div>
     
    </div>
  )
}

export default Home
